### ISSUE TITLE
Any way to trigger via boolean instead of timer?

### ISSUE THREAD

**Issue by SamCousinsGB** [joaopereirawd/fakeLoader.js#16]
I'm looking for a way to trigger it based on a boolean value.

Sometimes the time taken to execute an action differs, so I'd prefer to be able to set a flag to display whether to display the loader or not.

**Comment by changyushun** [comment]
jQuery Plugin:

1. add local var and public method
`var isStop = false;
        //console.log(isStop);
        $.fn.fakeLoader.stop = function () {
            isStop = true;
            //console.log('call outside ' + isStop);
        };`
2. check timeToHide is 0 or not, if 0 mean set interval timer to check 'isStop' value
`if (settings.timeToHide > 0) {
            setTimeout(function () {
                $(el).fadeOut();
            }, settings.timeToHide);
        }
        else {
            var timer = setInterval(function () {
                //console.log(isStop);
                if (isStop) {
                    $(el).fadeOut();
                    clearInterval(timer);
                }
            }, 200);
        }`

finally HTML code:
`var loader = $('#fakeLoader');
// show
loader.fakeLoader();
// disapear
loader.fakeLoader.stop();`

**Comment by SamCousinsGB** [comment]
Thanks @changyushun !
