### ISSUE TITLE
There is a bug when getting the window size in Firefox

### ISSUE THREAD

**Issue by Javirln** [joaopereirawd/fakeLoader.js#2]
When retrieving the Window's size using the jQuery function .width() and height() on the lines: 106 and 107 in the file fakeLoader.js/demo/js/fakeLoader.js, the functions return 0.

Please read:
http://stackoverflow.com/questions/12937494/why-does-firefox-return-0-as-the-value-of-window-height

Cheers

**Comment by joaopereirawd** [comment]
Hi all, 

**$(window)** calc was removed from fakeLoader.

Now you can see the spinners center in the browser window by CSS. 

Check what's new: 
https://github.com/joaopereirawd/fakeLoader.js/releases/tag/V2.0.0
