### ISSUE TITLE
plugin simply doesn't work

### ISSUE THREAD

**Issue by SundownDEV** [joaopereirawd/fakeLoader.js#20]
I followed the very simple guide at http://joaopereirawd.github.io/fakeLoader.js/

and the plugin doesn't work at all, I have the css and js files included, the call at the footer : 
`<script type="text/javascript">
    $("#fakeloader").fakeLoader({
        timeToHide:1200, //Time in milliseconds for fakeLoader disappear
        zIndex:"999",//Default zIndex
        spinner:"spinner1",//Options: 'spinner1', 'spinner2', 'spinner3', 'spinner4', 'spinner5', 'spinner6', 'spinner7'
        bgColor:"#2ecc71", //Hex, RGB or RGBA colors
        imagePath:"yourPath/customizedImage.gif" //If you want can you insert your custom image
    });
</script>`

jquery is also included version 2.1.4, I don't understand why this is not working :/ halp!!

edit: also nothing in the dev console of chrome.

**Comment by luisbajana** [comment]
Got the same problem with that jQuery version.

**Comment by SundownDEV** [comment]
Made my own fakeLoader in js but it still doesn't work

**Comment by luisbajana** [comment]
Yep, doing the same.

**Comment by nrileykc** [comment]
Issue is demo had the javascript and the div names off.  One is fakeloader other is fakeLoader.  Fix that and it's working for me.

**Comment by alfredrumss** [comment]
@nrileykc what version did you use?

**Comment by SundownDEV** [comment]
Issue was demo had the javascript and the div names off. One is fakeloader other is fakeLoader. Changing this is working.

Closing this as it was still open since a year.
