### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by Kalpesh300** [joaopereirawd/fakeLoader.js#29]
Isn't it available on npm? 
If no, will it be available on near future?
Thank you

**Comment by louisnelza** [comment]
I've fixed the error and published this library as an NPM module giving credit to the author.

https://www.npmjs.com/package/fakeloader

npm install fakeloader

**Comment by joaopereirawd** [comment]
Hi all

The fakeLoader.js was updated to V.2.0.0

You can now installing by npm or yarn: 
https://github.com/joaopereirawd/fakeLoader.js/blob/master/README.md

What's new in version 2.0: 
https://github.com/joaopereirawd/fakeLoader.js/releases/tag/V2.0.0
