### ISSUE TITLE
Bars Appears on Top Left Corner Before Centering

### ISSUE THREAD

**Issue by Behseini** [joaopereirawd/fakeLoader.js#3]
Hi,
First of all thank you for sharing this great plugin! I am trying to use your solution on This demo
<a href="http://bazikontarin.com/Paralax/">http://bazikontarin.com/Paralax</a>     Using Bootstrap 3 framework but for a reason the Bars appears first on top left corner and then moves to center! This might be watchable if you refresh the page several times!
Can you please let me know why this is happening? and how I can fix it? Thanks

**Comment by Behseini** [comment]
Hi Again, I just noticed that this issue is happening when I am using Bootstrap Carousel in the about Section !

**Comment by AlexRebula** [comment]
Hey Behseini. Have you found the solution to your problem? Does it still happen? 

I am doing some work on this plugin myself and I encounter a similar problem with a new element I added to the plugin. I solved the problem by the traditional way of first setting the 'display: none' CSS property to the newely added element and once the plugin is placed to the center I simply fade it in. If you still have this problem with your spinner this may be the solution.

BTW, can you show me the code that replicated the bug?

**Comment by AlexRebula** [comment]
Aha, I see this bug has been issued. It would be good if the author would close this issue then not to confuse us. :)

**Comment by juan-manuel-alberro** [comment]
I have the same issue and I fixed in this way (check the .hide() and .fadeIn() chained in the selector)

        function centerLoader() {

            var winW = $(window).width();
            var winH = $(window).height();

            var spinnerW = $('.fl').outerWidth();
            var spinnerH = $('.fl').outerHeight();

            $('.fl').hide().css({
                'position':'absolute',
                'left':(winW/2)-(spinnerW/2),
                'top':(winH/2)-(spinnerH/2)
            }).fadeIn();

        }
