### ISSUE TITLE
Uncaught TypeError: jQuery(...).fakeLoader is not a function

### ISSUE THREAD

**Issue by techmandan** [joaopereirawd/fakeLoader.js#31]
Hello. 
I know this is little bit old, but it's the best of what I found. I'm using newest jQuery(CDN). I'm new to jQuery, but other plugins normally works. I'm using full (fakeLoader.js) version. I'm trying to show it when user clicks button, because it starts uploading file. When I click the button, nothing hapens and in console, it show the following:
<img src="https://ctrlv.cz/shots/2018/08/19/Ymvd.png">
Why?
Thanks for answer

**Comment by zayabighead** [comment]
i think u should use the 1.11.1 version of jquery like he did

**Comment by joaopereirawd** [comment]
Hi @techmandan, @zayabighead,

The fakeLoader.js was updated to V.2.0.0. 

You may consider upgrade your version. 

Please check whats new in version 2.0.0:  
https://github.com/joaopereirawd/fakeLoader.js/releases
