### ISSUE TITLE
Error using script with jQuery 3.3.1

### ISSUE THREAD

**Issue by inglesuniversal** [joaopereirawd/fakeLoader.js#35]
Uncaught TypeError: e.indexOf is not a function
    at w.fn.init.w.fn.load (jquery.min.js:2)
    at fakeLoader.min.js:1
    at fakeLoader.min.js:1

Any pointers?

Regards

**Comment by joaopereirawd** [comment]
Hi @inglesuniversal  jQuery 3.3.1  is now supported! 
Try install the officially version of fakeLoader by npm or yarn:

**yarn add jq-fakeloader
or
npm i jq-fakeloader**



Check here whats new in the version 2.0 of fakeLoader:
https://github.com/joaopereirawd/fakeLoader.js/releases/tag/V2.0.0
